apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: nexuml
  # namespace: <username>
spec:
  elasticPolicy:
    rdzvBackend: c10d
    minReplicas: 1
    maxReplicas: 1
    maxRestarts: 10
  runPolicy:
    ttlSecondsAfterFinished: 100
    backoffLimit: 2
  pytorchReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          runtimeClassName: nvidia

          imagePullSecrets:
          - name: regcred
          
          volumes:
          - name: shared-mem
            emptyDir:
              sizeLimit: 4Gi # 2 GB are usually sufficient, use more if need be
              medium: Memory
          - name: local-storage
            emptyDir: {}
          - name: ram-storage
            emptyDir:
              medium: Memory
          - name: juicefs
            persistentVolumeClaim:
              claimName: juicefs
          - name: juicefs-prisma
            persistentVolumeClaim:
              claimName: juicefs-prisma
          # - name: ssh-key-volume
          #   secret:
          #     secretName: ssh-key-secret
          
          containers:
            - name: pytorch
              image: harbor.ika.rub.de/library/nexuml:latest
              command:
                - "torchrun"
                - "-m"
                - "nexuml"
                - "train"
                - "dcase-ast-adacos"
                - "--max-epochs"
                - "200"
              
              imagePullPolicy: Always # Always, IfNotPresent

              # envFrom:
              # - configMapRef:
              #     name: env-config
              # - configMapRef:
              #     name: git-config
              # - secretRef:
              #     name: ssh-key-secret
              # - secretRef:
              #     name: env-secret
              
              env:
              - name: OMP_NUM_THREADS  # Can be tuned for optimal performance
                value: "1"
              - name: NEXUML_DATA_ROOT
                value: /mnt/data
              - name: NEXUML_LOGS_ROOT
                value: /mnt/logs
              
              resources:
                limits:
                  nvidia.com/gpu: "1"
                  # cpu: 10
                  # memory: "60Gi"
              
              volumeMounts:
              - name: shared-mem
                mountPath: /dev/shm
              - name: local-storage
                mountPath: /mnt/local

              - name: juicefs-prisma
                subPathExpr: data
                mountPath: /mnt/data
              - name: juicefs-prisma
                subPathExpr: logs
                mountPath: /mnt/logs

              - name: juicefs
                mountPath: /workspace
                subPathExpr: code/nexuml
              - name: juicefs
                mountPath: /home/python-user/workspace
                subPathExpr: code/nexuml

              # - name: ssh-key-volume
              #   mountPath: /home/python-user/.ssh
              #   readOnly: false
              # - name: ssh-key-volume
              #   mountPath: /root/.ssh
              #   readOnly: false

          affinity:
            nodeAffinity:
              # What is required as a minimum
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: "nvidia.com/gpu.memory"
                    operator: Gt # (greater than)
                    # values: ["8000"] # 8 GB
                    values: ["12000"] # 12 GB
                  - key: "nvidia.com/cuda.runtime.major"
                    operator: Gt # (greater than)
                    values: ["11"]
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                    - Tesla-V100-SXM2-32GB
                    - NVIDIA-RTX-4000-Ada-Generation
                    - NVIDIA-GeForce-RTX-5080
                    - NVIDIA-GeForce-RTX-5070
                    - NVIDIA-GeForce-RTX-4090
                    - NVIDIA-GeForce-RTX-4070-SUPER
                    - NVIDIA-GeForce-RTX-4070
                    # - NVIDIA-GeForce-RTX-3060
                    # - NVIDIA-GeForce-RTX-2070
                    # - NVIDIA-GeForce-RTX-2060-SUPER
                    # - NVIDIA-GeForce-GTX-1080
          
          # nodeSelector:
          #   kubernetes.io/hostname: student-worker-5