changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 🧰 Maintenance
      labels:
        - chore
        - refactor
    - title: 📝 Documentation
      labels:
        - documentation
        - docs
    - title: Other Changes
      labels:
        - "*"   # catch-all: anything not matched above lands here