import {expect,test} from "@playwright/test";

test("typed settings, error focus, categorized drop, names and removable key routing",async({page},testInfo)=>{
  const failures:string[]=[];page.on("pageerror",error=>failures.push(error.message));
  page.on("dialog",dialog=>void dialog.accept());
  await page.goto("/");await page.getByLabel("Config path",{exact:true}).fill(process.env.STUDIO_CONFIG_PATH ?? "tiny.yaml");
  await page.getByRole("button",{name:"Open YAML",exact:true}).click();
  await expect(page.getByLabel("Search components")).toBeVisible({timeout:30000});
  await expect(page.getByRole("button",{name:"Open YAML",exact:true})).toBeEnabled({timeout:30000});
  await page.getByRole("button",{name:"Training",exact:true}).click();
  await expect(page.getByLabel("Execution backend",{exact:true})).toHaveValue("local:1");
  await page.getByLabel("Execution backend",{exact:true}).selectOption("ray-cluster:1");
  await page.locator('[data-field="execution.params.workers"]').filter({has:page.locator("option")}).selectOption({label:"integer"});
  await page.locator('input[data-field="execution.params.workers"]').fill("2");
  await expect(page.locator('input[data-field="execution.params.target.address"]')).toHaveValue("auto");
  await page.getByLabel("Execution backend",{exact:true}).selectOption("local:1");
  await page.getByLabel("Batch Size",{exact:true}).fill("0");
  await page.getByRole("button",{name:"Check fields",exact:true}).click();
  await expect(page.locator(".problems-list")).toContainText("training.batch_size",{timeout:30000});
  await page.getByRole("button",{name:"Pipeline",exact:true}).click();
  await page.locator(".problems-list").getByRole("button").filter({hasText:"training.batch_size"}).first().click();
  await expect(page.locator('.training-view')).toBeVisible();
  await expect(page.locator('input[data-field="training.batch_size"]')).toBeFocused();
  await page.getByLabel("Batch Size",{exact:true}).fill("8");
  await page.getByRole("button",{name:"Pipeline",exact:true}).click();
  await page.getByRole("button",{name:"Fit view",exact:true}).click();
  await expect(page.locator('.react-flow__edge').filter({has:page.locator('path')}).first()).toBeVisible();
  const firstEdge=page.locator('.react-flow__edge').first();
  await firstEdge.focus();await firstEdge.press("Enter");
  await expect(page.locator('.canvas-toolbar').getByRole("button",{name:"Remove connection",exact:true})).toBeVisible();
  await firstEdge.press("Delete");
  await page.getByRole("button",{name:"Undo",exact:true}).click();
  const point=await page.locator('.react-flow__edge-interaction').first().evaluate(element=>{
    const path=element as SVGPathElement;const point=path.getPointAtLength(path.getTotalLength()/2);const screen=point.matrixTransform(path.getScreenCTM()!);return {x:screen.x,y:screen.y};
  });
  await page.mouse.click(point.x,point.y);
  await page.locator('.canvas-toolbar').getByRole("button",{name:"Remove connection",exact:true}).click({timeout:5000});
  await page.getByRole("button",{name:"Undo",exact:true}).click();
  await page.getByLabel("Search components").fill("ResNet");
  await expect(page.locator(".component-list")).toContainText("Vision");
  await page.getByLabel("Search components").fill("LinearEncoder");
  const drag=page.locator('.component-list button').filter({hasText:"LinearEncoder"});
  const stage=page.locator('.react-flow__node[data-id="stage:Encoder"]');
  const before=await page.locator('.react-flow__node').count();
  await drag.dragTo(stage.locator('.node-heading'),{timeout:15000});
  await expect(page.locator('.react-flow__node')).toHaveCount(before+1);
  await page.getByLabel("Node display name").fill("Dragged encoder");
  await page.locator(".properties-panel summary").filter({hasText:"Key connections"}).click();
  await page.getByLabel("Connect new x input",{exact:true}).selectOption({label:"Data → features (x)"});
  await expect(page.locator('[data-field$=".keys_in.0"]')).toHaveValue("features");
  await page.getByRole("button",{name:"Remove connection features",exact:true}).click();
  await expect(page.locator('[data-field$=".keys_in.0"]')).toHaveValue("");
  await expect(page.getByRole("button",{name:"Run…",exact:true})).toBeDisabled();
  await page.getByRole("button",{name:"Undo",exact:true}).click();
  await expect(page.locator('[data-field$=".keys_in.0"]')).toHaveValue("features");
  await page.getByRole("button",{name:"YAML",exact:true}).click();
  const yaml=await page.getByLabel("Scenario YAML").inputValue();expect(yaml).not.toContain("Dragged encoder");
  await page.getByRole("button",{name:"Close YAML",exact:true}).click();
  await page.getByLabel("Config path",{exact:true}).fill(`authoring-${Date.now()}.yaml`);
  await page.getByRole("button",{name:"Save",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Configuration and separate layout saved.",{timeout:30000});
  await page.getByRole("button",{name:"Open YAML",exact:true}).click();
  await expect(page.getByRole("button",{name:"Open YAML",exact:true})).toBeEnabled({timeout:30000});
  await expect(page.locator(".react-flow__node")).toContainText(["Dragged encoder"]);
  await page.getByRole("button",{name:"Fit view",exact:true}).click();
  await page.screenshot({path:testInfo.outputPath("graph-first-desktop.png"),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.getByRole("button",{name:"Training",exact:true}).click();
  await page.screenshot({path:testInfo.outputPath("typed-settings-mobile.png"),fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(failures).toEqual([]);
});
