import {expect,test} from "@playwright/test";
import {parse} from "yaml";
import {check,fileAction,inspector,openFile,trainingSection} from "./helpers";

test("exact form types, automatic fields, inheritance and retained invalid/custom settings",async({page})=>{
  await page.goto("/");await openFile(page);
  const read=async()=>{await page.getByRole("button",{name:"YAML",exact:true}).click();const config=parse(await page.getByLabel("Scenario YAML").inputValue());await page.getByRole("button",{name:"Close YAML",exact:true}).click();return config;};
  const original=await read();
  await page.getByRole("button",{name:"Training",exact:true}).click();
  await page.getByLabel("Batch Size mode",{exact:true}).filter({visible:true}).selectOption({label:"Automatic"});
  await page.getByLabel("Min",{exact:true}).fill("2");await page.getByLabel("Max",{exact:true}).fill("32");await page.getByLabel("Safety",{exact:true}).selectOption("margin");await page.getByLabel("Margin",{exact:true}).fill("0.75");
  let config=await read();expect(config.training.batch_size).toEqual({mode:"auto",min:2,max:32,candidates:"power_of_two",safety:"margin",margin:.75});
  await page.getByLabel("Batch Size mode",{exact:true}).filter({visible:true}).selectOption({label:"Fixed"});
  await page.locator('input[data-field="training.batch_size"]').fill("8");
  await page.getByLabel("Learning rate",{exact:true}).fill("1e-2");expect((await read()).training.lr).toBe(.01);
  await page.getByRole("button",{name:"Undo",exact:true}).click();await expect(page.getByLabel("Learning rate",{exact:true})).toHaveValue(String(original.training.lr));expect((await read()).training.lr).toBe(original.training.lr);
  await page.getByRole("button",{name:"Redo",exact:true}).click();await expect(page.getByLabel("Learning rate",{exact:true})).toHaveValue("0.01");await page.getByRole("button",{name:"Undo",exact:true}).click();
  await page.getByLabel("Learning rate",{exact:true}).fill("1e-");
  await trainingSection(page,"Data loading");await trainingSection(page,"Basics");
  await expect(page.getByLabel("Learning rate",{exact:true})).toHaveValue("1e-");
  await check(page);await expect(page.locator(".problems-list")).toContainText("training.lr");
  await trainingSection(page,"Execution");await page.locator(".problems-list button").filter({hasText:"training.lr"}).click();
  await expect(page.getByLabel("Learning rate",{exact:true})).toBeFocused();await page.getByLabel("Learning rate",{exact:true}).fill("1e-3");
  await page.locator('.training-content article:not([hidden])> .fields>details>summary').filter({hasText:"Raw configuration"}).click();
  const raw=await page.getByLabel("Raw training settings",{exact:true}).inputValue();
  await page.getByLabel("Raw training settings",{exact:true}).fill("{invalid");await page.getByRole("button",{name:"Apply Raw training settings",exact:true}).click();
  await trainingSection(page,"Data loading");await trainingSection(page,"Basics");await expect(page.getByLabel("Raw training settings",{exact:true})).toHaveValue("{invalid");
  await page.getByLabel("Raw training settings",{exact:true}).fill(raw);
  await trainingSection(page,"Data loading");
  await page.getByLabel("Batch Size mode",{exact:true}).filter({visible:true}).selectOption({label:"Set value"});
  await page.locator('input[data-field="data.loader.batch_size"]').filter({visible:true}).fill("4");
  await trainingSection(page,"Basics");await expect(page.locator(".training-content .buffer-notice")).toContainText("overrides training batch size: 4");
  await page.getByRole("button",{name:"Edit loader override",exact:true}).click();
  await page.getByLabel("Batch Size mode",{exact:true}).filter({visible:true}).selectOption({label:"Use training batch size"});
  await trainingSection(page,"Optimizer and schedule");
  await page.getByLabel("Warmup mode",{exact:true}).selectOption({label:"string"});await page.getByLabel("Warmup",{exact:true}).fill("0.1");config=await read();expect(config.training.scheduler.warmup).toBe("0.1");
  await page.getByLabel("Warmup mode",{exact:true}).selectOption({label:"integer"});await page.getByLabel("Warmup",{exact:true}).fill("2");
  await page.locator('.training-content article:not([hidden])>.fields>details>summary').filter({hasText:"Raw configuration"}).click();
  const factories=JSON.parse(await page.getByLabel("Raw optimizer settings",{exact:true}).inputValue());
  factories.optimizer.args=[.9];factories.optimizer.kwargs={lr:.002,weight_decay:.01};
  await page.getByLabel("Raw optimizer settings",{exact:true}).fill(JSON.stringify(factories));await page.getByRole("button",{name:"Apply Raw optimizer settings",exact:true}).click();
  await expect(page.getByRole("button",{name:"Apply Raw optimizer settings",exact:true})).toHaveCount(0);
  await trainingSection(page,"Checkpoints and logging");await page.getByLabel("Resume Trainer checkpoint",{exact:true}).fill("retained.ckpt");await trainingSection(page,"Basics");await trainingSection(page,"Checkpoints and logging");await expect(page.getByLabel("Resume Trainer checkpoint",{exact:true})).toHaveValue("retained.ckpt");await page.getByLabel("Resume Trainer checkpoint",{exact:true}).fill("");
  config=await read();expect(config.training.batch_size).toBe(8);expect(config.data.loader.batch_size).toBeNull();expect(config.training.lr).toBe(.001);expect(config.training.scheduler.warmup).toBe(2);expect(config.training.optimizer.args).toEqual([.9]);expect(config.training.optimizer.kwargs).toEqual({lr:.002,weight_decay:.01});
  expect(config.pipeline).toEqual(original.pipeline);expect(config.logging).toEqual(original.logging);expect(config.evaluation).toEqual(original.evaluation);
  const path=`training-ux-${Date.now()}.yaml`;await fileAction(page,"Save as…");await page.getByLabel("Config path",{exact:true}).fill(path);await page.getByRole("button",{name:"Save file",exact:true}).click();await expect(page.getByRole("dialog")).toBeHidden({timeout:30000});
  await page.getByRole("button",{name:"Pipeline",exact:true}).click();await openFile(page,path);expect(await read()).toEqual(config);
  await page.locator(".outline").getByRole("button",{name:"1. LinearEncoder",exact:true}).first().click();
  await page.getByLabel("Output Dim",{exact:true}).fill("-");await inspector(page,"Routing");await inspector(page,"Settings");await expect(page.getByLabel("Output Dim",{exact:true})).toHaveValue("-");await page.getByLabel("Output Dim",{exact:true}).fill("2");
});
