import { expect, test } from "@playwright/test";

test("real CPU config edit/save/check/build/train/reconnect/export and corporate responsive shell",async({page},testInfo)=>{
  const failures:string[]=[];const external:string[]=[];
  page.on("pageerror",error=>failures.push(error.message));
  page.on("request",request=>{if(!["127.0.0.1","localhost"].includes(new URL(request.url()).hostname))external.push(request.url());});
  page.on("dialog",dialog=>void dialog.accept());
  await page.goto("/");
  await expect(page.getByRole("button",{name:"Resolve recipe"})).toBeVisible();
  await page.getByLabel("Discovered scenario").selectOption("synthetic-linear-ae-reconstruction");
  await page.getByRole("button",{name:"Resolve recipe",exact:true}).press("Enter");
  await expect(page.getByLabel("Search components")).toBeVisible();
  await expect(page.getByRole("button",{name:"Resolve recipe",exact:true})).toBeEnabled({timeout:30000});
  await page.getByLabel("Config path",{exact:true}).fill(process.env.STUDIO_CONFIG_PATH ?? "tiny.yaml");
  await page.getByRole("button",{name:"Open YAML",exact:true}).click();
  await expect(page.getByRole("button",{name:"Open YAML",exact:true})).toBeEnabled({timeout:30000});
  await expect(page.getByLabel("Search components")).toBeVisible();
  await expect(page.locator('.react-flow__node[data-id="data"]')).toBeVisible();
  if(process.env.STUDIO_LIBRARY_ROOT){
    await expect(page.getByRole("status")).toContainText("Stale layout ignored.");
    await page.getByRole("button",{name:"Libraries",exact:true}).click();
    await page.getByLabel("Local library root",{exact:true}).fill(process.env.STUDIO_LIBRARY_ROOT);
    await page.getByRole("button",{name:"Add root",exact:true}).click();
    await page.getByLabel("Search components").fill("studio-smoke-scale");
    await page.locator(".component-list").getByRole("button",{name:/studio-smoke-scale/}).click();
    await expect(page.getByLabel("Scale",{exact:true})).toHaveValue("1");
    await page.getByLabel("Scale",{exact:true}).fill("2");
    await page.getByRole("button",{name:"Move studio-smoke-scale up",exact:true}).press("Enter");
    await page.getByRole("button",{name:"Undo",exact:true}).press("Enter");
    await page.getByRole("button",{name:"Remove layer",exact:true}).click();
    await page.getByRole("button",{name:"Remove root",exact:true}).click();
    await expect(page.locator(".component-list").getByRole("button",{name:/studio-smoke-scale/})).toHaveCount(0);
    await page.getByLabel("Search components").fill("");
    await page.getByRole("button",{name:"Libraries",exact:true}).click();
  }
  await page.getByRole("button",{name:"Move stage Encoder down",exact:true}).press("Enter");
  await page.getByRole("button",{name:"Undo",exact:true}).press("Enter");
  await page.getByRole("button",{name:"1. LinearEncoder",exact:true}).nth(1).click();
  await page.locator(".properties-panel summary").filter({hasText:"Key connections"}).click();
  await page.getByLabel("Connect latent",{exact:true}).selectOption({label:"Data → features (x)"});
  await expect(page.getByLabel("keys_in",{exact:true})).toHaveValue(/features/);
  await page.getByRole("button",{name:"Undo",exact:true}).press("Enter");
  await expect(page.getByLabel("keys_in",{exact:true})).toHaveValue(/latent/);
  await page.locator(".panel-settings summary").click();
  await page.getByLabel("Component panel width",{exact:true}).press("ArrowRight");
  await page.getByRole("button",{name:"Component panel",exact:true}).press("Enter");
  await expect(page.getByLabel("Search components")).toBeHidden();
  await page.getByRole("button",{name:"Component panel",exact:true}).press("Enter");
  await page.locator(".panel-settings summary").click();
  await page.getByRole("button",{name:"1. LinearEncoder",exact:true}).first().click();
  await expect(page.getByLabel("Output Dim",{exact:true})).toBeVisible();
  const keys=await page.getByLabel("keys_in",{exact:true}).inputValue();
  await page.getByLabel("keys_in",{exact:true}).fill("null");
  await page.getByRole("button",{name:"Apply keys_in",exact:true}).click();
  await expect(page.locator(".properties-panel .field-error").first()).toContainText("buffer is retained",{timeout:30000});
  await expect(page.getByLabel("keys_in",{exact:true})).toHaveValue("null");
  await expect(page.locator('.react-flow__node[data-id="data"]')).toBeVisible();
  await page.getByLabel("keys_in",{exact:true}).fill(keys);
  await page.getByLabel("Output Dim",{exact:true}).fill("4");
  await page.getByRole("button",{name:"Undo",exact:true}).click();
  await expect(page.getByLabel("Output Dim",{exact:true})).toHaveValue("2");
  await page.getByRole("button",{name:"Redo",exact:true}).click();
  await expect(page.getByLabel("Output Dim",{exact:true})).toHaveValue("4");
  await page.getByRole("button",{name:"Undo",exact:true}).click();
  await page.locator(".properties-panel summary").filter({hasText:"Visual position"}).click();
  await page.getByLabel("Node position x",{exact:true}).fill("40");
  await page.getByLabel("Config path",{exact:true}).fill(`browser-saved-${Date.now()}.yaml`);
  await page.getByRole("button",{name:"Save",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Configuration and separate layout saved.",{timeout:30000});
  await page.getByRole("button",{name:"Open YAML",exact:true}).click();
  await expect(page.getByRole("button",{name:"Open YAML",exact:true})).toBeEnabled({timeout:30000});
  await page.getByRole("button",{name:"1. LinearEncoder",exact:true}).first().click();
  if(!await page.getByLabel("Node position x",{exact:true}).isVisible())await page.locator(".properties-panel summary").filter({hasText:"Visual position"}).click();
  await expect(page.getByLabel("Node position x",{exact:true})).toHaveValue("40");
  await page.getByRole("button",{name:"YAML",exact:true}).click();
  const buffer=await page.getByLabel("Scenario YAML").inputValue();
  await page.getByLabel("Scenario YAML").fill("invalid: [yaml");
  await page.getByRole("button",{name:"Apply YAML",exact:true}).click();
  await expect(page.getByRole("status")).not.toContainText("Waiting");
  await expect(page.getByLabel("Scenario YAML")).toHaveValue("invalid: [yaml");
  await expect(page.getByLabel("Output Dim",{exact:true})).toBeDisabled();
  await page.getByLabel("Scenario YAML").fill(buffer.replace("LinearEncoder","missing-studio-definition"));
  await page.getByRole("button",{name:"Apply YAML",exact:true}).click();
  await expect(page.getByRole("status")).not.toContainText("Waiting");
  await expect(page.getByLabel("Scenario YAML")).toHaveValue(/missing-studio-definition/);
  await page.getByLabel("Scenario YAML").fill(buffer);
  await page.getByRole("button",{name:"Apply YAML",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("YAML applied",{timeout:30000});
  await page.getByRole("button",{name:"Close YAML",exact:true}).click();
  await expect(page.locator('.react-flow__node[data-id="data"]')).toBeVisible();
  await page.getByRole("button",{name:"Check fields",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Fields valid",{timeout:30000});
  await page.getByRole("button",{name:"Build check (executes code)",exact:true}).press("Enter");
  await expect(page.locator(".build-state")).toContainText("succeeded",{timeout:30000});
  await expect(page.locator(".build-state")).toContainText("reconstructed");
  await page.getByLabel("Output Dim",{exact:true}).fill("4");
  await expect(page.locator(".build-state")).toContainText("stale");
  await page.getByRole("button",{name:"Undo",exact:true}).click();
  await page.getByRole("button",{name:"Fit view",exact:true}).click();
  await expect(page.locator(".react-flow__edge").first()).toBeVisible();
  await expect.poll(()=>page.locator('.react-flow__node[data-id="data"]').evaluate(element=>element.getBoundingClientRect().width)).toBeGreaterThan(75);
  await page.locator(".properties-panel").evaluate(element=>{element.scrollTop=0;});
  await page.screenshot({path:testInfo.outputPath("desktop-pipeline.png"),fullPage:true});
  expect(await page.locator("body").evaluate(element=>getComputedStyle(element).backgroundColor)).toBe("rgb(16, 16, 16)");
  const action=page.getByRole("button",{name:"Run…",exact:true});
  expect(await action.evaluate(element=>[getComputedStyle(element).backgroundColor,getComputedStyle(element).color])).toEqual(["rgb(24, 143, 213)","rgb(0, 0, 0)"]);
  await action.click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.getByRole("button",{name:"Confirm & start training",exact:true}).click();
  await expect(page.getByLabel("Observed operation")).not.toHaveValue("");
  await page.getByRole("button",{name:"Training",exact:true}).click();
  await page.getByLabel("Batch Size",{exact:true}).fill("16");
  await page.getByRole("button",{name:"Execution",exact:true}).click();
  await expect(page.locator(".status-grid")).toContainText("succeeded",{timeout:45000});
  await expect(page.locator(".metric")).not.toHaveCount(0);
  await page.getByRole("button",{name:"Inspect launch config",exact:true}).click();
  await expect(page.locator("details").filter({hasText:"Frozen launch configuration"})).toContainText("batch_size: 8");
  const identity=await page.getByLabel("Observed operation").inputValue();
  await page.reload();
  await page.getByRole("button",{name:"Execution",exact:true}).click();
  await page.getByLabel("Observed operation").selectOption(identity);
  await expect(page.locator(".status-grid")).toContainText("succeeded",{timeout:30000});
  await expect(page.locator(".metric")).not.toHaveCount(0);
  await page.getByRole("button",{name:"Artifacts",exact:true}).click();
  await page.getByLabel("Export path",{exact:true}).fill(`browser-export-${Date.now()}`);
  await page.getByRole("button",{name:"Export trained checkpoint",exact:true}).click();
  await expect(page.getByLabel("Observed operation")).not.toHaveValue(identity,{timeout:30000});
  await expect(page.locator("summary").filter({hasText:"Frozen launch configuration"})).toHaveCount(0);
  await expect(page.locator(".status-grid")).toContainText("succeeded",{timeout:30000});
  await expect(page.locator(".artifact-list")).toContainText("resolved_config.yaml",{timeout:30000});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:testInfo.outputPath("mobile-artifacts.png"),fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole("button",{name:"Pipeline",exact:true}).click();
  await page.getByLabel("Config path",{exact:true}).fill(process.env.STUDIO_CONFIG_PATH ?? "tiny.yaml");
  await page.getByRole("button",{name:"Open YAML",exact:true}).click();
  await expect(page.getByRole("button",{name:"Canvas",exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Properties",exact:true}).click();
  await expect(page.locator(".properties-panel")).toBeVisible();
  await page.screenshot({path:testInfo.outputPath("mobile-pipeline.png"),fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.setViewportSize({width:1024,height:900});
  await page.getByRole("button",{name:"Canvas",exact:true}).click();
  await page.screenshot({path:testInfo.outputPath("tablet-pipeline.png"),fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(external).toEqual([]);expect(failures).toEqual([]);
});
